cmake_minimum_required(VERSION 3.20)
project(icarus_1d LANGUAGES C)                          # specifies what language/toolset to use 
set(CMAKE_C_STANDARD 11)                                # magic var: c11 version 
set(CMAKE_C_STANDARD_REQUIRED ON)                       # magic var: enforce version
set(CMAKE_C_EXTENSIONS OFF)                             # magic var: MISRA forbids most GNU extensions

# conditionally include flags & driver headers related to the STM32 board
if(CMAKE_C_COMPILER MATCHES "arm-none-eabi")
  enable_language(ASM)                                  # enable ASM to execute init.s file for board 
  
  file(GLOB BSP_SOURCES src/bsp/nucleo_f446re/*.c)           
  file(GLOB BSP_ASM     src/bsp/nucleo_f446re/*.s)

  set(LL_SOURCES                                        # selectively include driver files as needed
    lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c
    lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c
    lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c
    lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c
    lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c
  )

  add_executable(fw_hover ${LL_SOURCES} ${BSP_SOURCES} ${BSP_ASM}) # main included through bsp/board.c

  # pass flags to Make directive to set board macros across all source files
  # i.e. arm-eabi-none-gcc -DSTM32F446xx -DUSE_FULL_LL_DRIVER -DHSE_VALUE=8000000
  target_compile_definitions(fw_hover PRIVATE     # -> passed flags are limited to this target scope (not other linked targets)

    STM32F446xx                                   # -> selects the corresponding codeblocks for the F446 chip variant in stm32f4xx.h (-DSTM32F446xx)
                                                  #   - sets compiler flag -DSTM32F446xx which defines a corresponding macro in all C files

    USE_FULL_LL_DRIVER                            # -> sets the boolean flag to enable LL function bodies (see stm32f4xx_ll_*.c files)
                                                  #   - sets compiler flag -DUSE_FULL_LL_DRIVER which defines a corresponding macro in all C files
                                                  
    HSE_VALUE=8000000                             # -> macro representing 8mhz clk speed, sourced from ST-Link clk
                                                  #   - note: clk config is actually performed in the board.c file, by SystemClock_Config()
                                                  #   - this flag just overrides the macro default value of 25MHz -> -DHSE_VALUE=8000000
                                                  #   - SystemClock_Config(): generated by CubeMX
                                                  #       - writes to RCC regs, selects HSE as PLL src, sets PLLM/N/P, switches SYSCLK to PLLCLK
  )

  # include paths to specify to the compiler where to find headers
  target_include_directories(fw_hover PRIVATE
    src/bsp/nucleo_f446re                    # -> includes src/bsp/nucleo_f446re directory in the file search path:
                                             #   - this includes the CubeMX generated: 
                                             #      - main.h: includes usart/rcc/gpio LL headers, board pin macros, error handlers
                                             #      - stm32f4xx_it.h: interrupt handlers (NVIC priority groups)
                                             #      - stm32_assert.h: runtime parameter checks (enabled by USE_FULL_ASSERT)
    lib/CMSIS/Device/ST/STM32F4xx/Include    # -> includes CubeMX generated peripheral register definitions (one per peripheral)
    lib/CMSIS/Include                        # -> includes Cortex-M peripherals (NVIC, SysTick, FPU, MPU)
    lib/STM32F4xx_HAL_Driver/Inc             # -> includes LL & HAL wrapper functions for register access
  )

  # tells the linker how to link the compiled .o files into a final .elf binary  
  target_link_options(fw_hover PRIVATE  
    -T${CMAKE_SOURCE_DIR}/src/bsp/nucleo_f446re/STM32F446XX_FLASH.ld     # -> CubeMX generated linker script, 
                                                                            #   - defines flash + RAM regions
                                                                            #   - specifies where to place each section
                                                                            # -> note: linker flags (CPU_FLAGS) defined in compiler setup script 
    --specs=nano.specs                                                      # -> use newlib-nano: condensed embedded C lib (covers printf, malloc, memcpy, etc.) 
    -Wl,--gc-sections                                                       # -> strip unused funcitons/data from final bin
  )

  # .elf -> .bin conversion
  add_custom_command(TARGET fw_hover POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:fw_hover> fw_hover.bin
  )

else()
  add_executable(lh_hover src/main.c) 
endif()
