name: 1d-stabilizer CI 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  one-d-host-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1d_stabilizer
    steps:
      - uses: actions/checkout@v5

      - name: build 1b-stabilizer
        run: cmake -S . -B build/host && cmake --build build/host

      - name: install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: check MISRA compatibility
        run: cppcheck --addon=misra --std=c11 --error-exitcode=1 src 
